version: '3'
services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    command: bash ./tasks/ci/build
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      SHOP_ID_1: ${SHOP_ID_1}
      SHOP_TOKEN_1: ${SHOP_TOKEN_1}
    command: bash ./tasks/ci/integration
  publish:
    build:
      context: .
      dockerfile: publish.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    command: bash ./tasks/ci/publish