version: '3'
services:
  build:
    build:
      context: .
      dockerfile: build.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    command: bash ./tasks/ci/build
  deploy:
    build:
      context: .
      dockerfile: deploy.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      HOST_URL: ${HOST_URL}
      SHOPIFY_API_KEY: ${SHOPIFY_API_KEY}
      SHOPIFY_API_SECRET_KEY: ${SHOPIFY_API_SECRET_KEY}
      TABLE_NAME: ${TABLE_NAME}
    command: bash ./tasks/ci/deploy
  integration:
    build:
      context: .
      dockerfile: integration.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      SHOP_ID_1: ${SHOP_ID_1}
      SHOP_TOKEN_1: ${SHOP_TOKEN_1}
      SHOPIFY_API_SECRET_KEY: ${SHOPIFY_API_SECRET_KEY}
      API_URL: ${API_URL}
      TABLE_NAME: ${TABLE_NAME}
    command: bash ./tasks/ci/integration
  publish:
    build:
      context: .
      dockerfile: publish.Dockerfile
    volumes:
      - ../../:/app
    working_dir: /app
    environment:
      NPM_TOKEN: ${NPM_TOKEN}
    command: bash ./tasks/ci/publish