name: pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        required: true
        default: "prerelease"
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          HOST_URL: ${{ secrets.HOST_URL }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET_KEY: ${{ secrets.SHOPIFY_API_SECRET_KEY }}
          TABLE_NAME: ShopifyTable
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build deploy
          docker-compose -f tasks/ci/docker-compose.yml run deploy
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: integration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SHOP_ID_1: ${{ secrets.SHOP_ID_1 }}
          SHOP_TOKEN_1: ${{ secrets.SHOP_TOKEN_1 }}
          SHOPIFY_API_KEY: ${{ secrets.SHOPIFY_API_KEY }}
          SHOPIFY_API_SECRET_KEY: ${{ secrets.SHOPIFY_API_SECRET_KEY }}
          API_URL: ${{ secrets.HOST_URL }}
          TABLE_NAME: ShopifyTable
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build integration
          docker-compose -f tasks/ci/docker-compose.yml run integration
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish
          docker-compose -f tasks/ci/docker-compose.yml run publish
          docker-compose -f tasks/ci/docker-compose.yml down
