name: pipeline
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      publish:
        required: true
        default: "prerelease"
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build build
          docker-compose -f tasks/ci/docker-compose.yml run build
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: integration
        env:
          SHOP_ID_1: ${{ secrets.SHOP_ID_1 }}
          SHOP_TOKEN_1: ${{ secrets.SHOP_TOKEN_1 }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build integration
          docker-compose -f tasks/ci/docker-compose.yml run integration
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: publish_prerelease
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish_prerelease
          docker-compose -f tasks/ci/docker-compose.yml run publish_prerelease
          docker-compose -f tasks/ci/docker-compose.yml down
      - name: publish_release
        if: ${{ github.event.inputs.publish == 'release' }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          docker-compose -f tasks/ci/docker-compose.yml build publish_release
          docker-compose -f tasks/ci/docker-compose.yml run publish_release
          docker-compose -f tasks/ci/docker-compose.yml down
